export enum ProductType {
	RING = 'RING',
	NECKLACE = 'NECKLACE',
	BRACELET = 'BRACELET',
	EARRING = 'EARRING',
	SET = 'SET',
	WATCH = 'WATCH',
	BROOCH = 'BROOCH',
	CHAIN = 'CHAIN',
	GOLD_BAR = 'GOLD_BAR',
	OTHER = 'OTHER',
}

export enum ProductStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum ProductMaterial {
	GOLD = 'GOLD',
	WHITE_GOLD = 'WHITE_GOLD',
	ROSE_GOLD = 'ROSE_GOLD',
	SILVER = 'SILVER',
	PLATINUM = 'PLATINUM',
	DIAMOND = 'DIAMOND',
	PEARL = 'PEARL',
	TITANIUM = 'TITANIUM',
	STAINLESS_STEEL = 'STAINLESS_STEEL',
	BRASS = 'BRASS',
	COPPER = 'COPPER',
	LEATHER = 'LEATHER',
	OTHER = 'OTHER',
}

export enum ProductLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	GYEONGJU = 'GYEONGJU',
	GWANGJU = 'GWANGJU',
	CHONJU = 'CHONJU',
	DAEJON = 'DAEJON',
	JEJU = 'JEJU',
}
